### ISSUE TITLE
Control Center - Failed to start

### ISSUE THREAD

**Issue by lduparc** [confluentinc/cp-ansible#105]
Control center failed to start using systemd service but is working using command line:

Using systemd we have the following error : 
```
org.apache.kafka.streams.errors.StreamsException: task [0_0] Fatal error while trying to lock the state directory for task 0_0
	at org.apache.kafka.streams.processor.internals.AbstractTask.registerStateStores(AbstractTask.java:223)
	at org.apache.kafka.streams.processor.internals.StreamTask.initializeStateStores(StreamTask.java:257)
	at org.apache.kafka.streams.processor.internals.AssignedTasks.initializeNewTasks(AssignedTasks.java:72)
	at org.apache.kafka.streams.processor.internals.TaskManager.updateNewAndRestoringTasks(TaskManager.java:325)
	at org.apache.kafka.streams.processor.internals.StreamThread.runOnce(StreamThread.java:866)
	at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:804)
	at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:773)
[2019-06-19 09:27:12,308] INFO [main] unable to get command store (io.confluent.command.CommandStore)
[2019-06-19 09:27:13,309] INFO [main] unable to get command store (io.confluent.command.CommandStore)
[2019-06-19 09:27:14,309] INFO [main] unable to get command store (io.confluent.command.CommandStore)
...
```

using command line :
`/usr/bin/control-center-start /etc/confluent-control-center/control-center-production.properties`

>> Control center start and stay up and running

Command is the same command used by systemd service. Only User/Group change

**Comment by JumaX** [comment]
@lduparc The error is stating that Control Center is unable to lock the required directories it needs to setup its command store.  I suspect the user/group change you speak of is the root cause, in that it doesn't have the right permissions in place for Control Center to access directories.

**Comment by lduparc** [comment]
Yes it seems to be permissions issue with user/group but I change nothing on role confluent.control-center.

**Comment by JumaX** [comment]
@lduparc apologies, not sure I understand completely.  I think what has probably happened, is that when you changed the user/group, it changed the permissions on the directory, which Control Center can no longer access.  I would check the permissions on your file system and try opening them up.

**Comment by tanermelikoglu** [comment]
@lduparc what is the solution ?

**Comment by JumaX** [comment]
@tanermelikoglu The solution was a permissions problem with the user and group starting the service.  @lduparc stated that it worked with a different user/group then probably what it was installed with.

**Comment by tanermelikoglu** [comment]
@JumaX i am starting the service inside of docker image via Entrypoint that has the root perms but get the same error. Any ideas why ?

**Comment by JumaX** [comment]
@tanermelikoglu  Are you deploying with CP-Ansible?  Also I am not familiar with Entrypoint.  Hard to say without logs.  If you are using CP-Ansible, I would recommend opening a new issue and fill out the issue template with more details.  You can also open a ticket with our support team if you have a support subscription at support.confluent.io.

**Comment by domenicbove** [comment]
@tanermelikoglu if you plan to run confluent in containers, cp-ansible might not be your best option because we ship docker images, and have example configuration in docker-compose files.

But I think if you are looking to run the services you should use systemctl instead of the Entrypoint command... ie
```
systemctl start confluent-control-center
```
This should start the process with the correct user.

@JumaX  is correct, a new issue seems like a good idea, if systemctl does not work.
