### ISSUE TITLE
Confluent Install - Generated certs - What is the password

### ISSUE THREAD

**Issue by adbdkb** [confluentinc/cp-ansible#1454]
Confluent Install - Generated certs - What is the password

**Describe the issue**
I am installing Confluent on a sandbox and allowed the process to generate the required certs.  Now I was to create topics using Confluent CLI and I passed the client.properties file for --config parameter.   I tried "changeit" as password for the jks, but that is not working.  I also tried blank password, which also gives a different error.

What is the default password for the certs generated by the process, so I can create topics using confluent-cli

**Comment by adbdkb** [comment]
This is the error I get when running /bin/kafka-topics  -  when I put  "" for password 

Exception in thread "main" org.apache.kafka.common.KafkaException: Failed to create new KafkaAdminClient
        at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:587)
        at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:516)
        at org.apache.kafka.clients.admin.Admin.create(Admin.java:133)
        at kafka.admin.TopicCommand$TopicService$.createAdminClient(TopicCommand.scala:253)
        at kafka.admin.TopicCommand$TopicService$.apply(TopicCommand.scala:257)
        at kafka.admin.TopicCommand$.main(TopicCommand.scala:51)
        at kafka.admin.TopicCommand.main(TopicCommand.scala)
Caused by: org.apache.kafka.common.KafkaException: org.apache.kafka.common.KafkaException: Failed to load SSL keystore /var/ssl/private/kafka_broker.keystore.jks of type JKS
        at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:193)
        at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:233)
        at org.apache.kafka.common.network.ChannelBuilders.clientChannelBuilder(ChannelBuilders.java:82)
        at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:120)
        at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:555)
        ... 6 more
Caused by: org.apache.kafka.common.KafkaException: Failed to load SSL keystore /var/ssl/private/kafka_broker.keystore.jks of type JKS
        at org.apache.kafka.common.security.ssl.DefaultSslEngineFactory$FileBasedStore.load(DefaultSslEngineFactory.java:428)
        at org.apache.kafka.common.security.ssl.DefaultSslEngineFactory$FileBasedStore.<init>(DefaultSslEngineFactory.java:400)
        at org.apache.kafka.common.security.ssl.DefaultSslEngineFactory.createKeystore(DefaultSslEngineFactory.java:299)
        at org.apache.kafka.common.security.ssl.DefaultSslEngineFactory.configure(DefaultSslEngineFactory.java:161)
        at org.apache.kafka.common.security.ssl.SslFactory.instantiateSslEngineFactory(SslFactory.java:147)
        at org.apache.kafka.common.security.ssl.SslFactory.configure(SslFactory.java:97)
        at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:189)
        ... 10 more
Caused by: java.io.IOException: keystore password was incorrect
        at sun.security.pkcs12.PKCS12KeyStore.engineLoad(PKCS12KeyStore.java:2089)
        at sun.security.provider.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:238)
        at sun.security.provider.JavaKeyStore$DualFormatJKS.engineLoad(JavaKeyStore.java:71)
        at java.security.KeyStore.load(KeyStore.java:1445)
        at org.apache.kafka.common.security.ssl.DefaultSslEngineFactory$FileBasedStore.load(DefaultSslEngineFactory.java:425)
        ... 16 more
Caused by: java.security.UnrecoverableKeyException: failed to decrypt safe contents entry: javax.crypto.BadPaddingException: Given final block not properly padded. Such issues can arise if a bad key is used during decryption.
        ... 21 more
