### ISSUE TITLE
Kafka SSL 

### ISSUE THREAD

**Issue by DefunctExodus** [confluentinc/cp-ansible#181]
I'm running into the following issue running this on RHEL7

```
[2020-02-04 06:15:40,257] ERROR [KafkaServer id=1] Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
org.apache.kafka.common.KafkaException: org.apache.kafka.common.KafkaException: org.apache.kafka.common.KafkaException: Failed to load SSL keystore /var/ssl/private/kafka_broker.keystore.jks of type JKS
	at org.apache.kafka.common.network.SslChannelBuilder.configure(SslChannelBuilder.java:71)
	at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:146)
	at org.apache.kafka.common.network.ChannelBuilders.serverChannelBuilder(ChannelBuilders.java:85)
	at kafka.network.Processor.<init>(SocketServer.scala:753)
	at kafka.network.SocketServer.newProcessor(SocketServer.scala:394)
	at kafka.network.SocketServer.$anonfun$addDataPlaneProcessors$1(SocketServer.scala:279)
	at kafka.network.SocketServer.addDataPlaneProcessors(SocketServer.scala:278)
	at kafka.network.SocketServer.$anonfun$createDataPlaneAcceptorsAndProcessors$1(SocketServer.scala:241)
	at kafka.network.SocketServer.$anonfun$createDataPlaneAcceptorsAndProcessors$1$adapted(SocketServer.scala:238)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at kafka.network.SocketServer.createDataPlaneAcceptorsAndProcessors(SocketServer.scala:238)
	at kafka.network.SocketServer.startup(SocketServer.scala:121)
	at kafka.server.KafkaServer.startup(KafkaServer.scala:263)
	at io.confluent.support.metrics.SupportedServerStartable.startup(SupportedServerStartable.java:114)
	at io.confluent.support.metrics.SupportedKafka.main(SupportedKafka.java:66)
Caused by: org.apache.kafka.common.KafkaException: org.apache.kafka.common.KafkaException: Failed to load SSL keystore /var/ssl/private/kafka_broker.keystore.jks of type JKS
	at org.apache.kafka.common.security.ssl.SslEngineBuilder.createSSLContext(SslEngineBuilder.java:163)
	at org.apache.kafka.common.security.ssl.SslEngineBuilder.<init>(SslEngineBuilder.java:104)
	at org.apache.kafka.common.security.ssl.SslFactory.configure(SslFactory.java:95)
	at org.apache.kafka.common.network.SslChannelBuilder.configure(SslChannelBuilder.java:69)

```

They keys are in fact there but the user `cp-kafka` does not have permission to read them

```
[hostname]# ll /var/ssl/private/
total 12
-rw-r-----. 1 root root 4701 Feb  4 06:13 kafka_broker.keystore.jks
-rw-r-----. 1 root root 1218 Feb  4 06:13 kafka_broker.truststore.jks
```

**Comment by JumaX** [comment]
@DefunctExodus Thanks for reaching out.  In order to be of assistance, can you do/answer the following:

1. Confirm the version of ansible you are running `ansible --version`

2. Confirm the version of the playbook you are running

3. Confirm the exact command you are running to execute the playbook

4. Confirm the options you have selected in your hosts file, for example, the variable set under the TLS section.

Thanks!

**Comment by DefunctExodus** [comment]
Sure.

1.  `ansible 2.8.3`  
2. ```On branch 5.4.0-post Your branch is up to date with 'origin/5.4.0-post'. ```
3. ```ansible-playbook  -i hosts.yaml all.yml```
4. Relevant variables
```
  confluent_server_enabled: false
  kafka_broker_schema_validation_enabled: false
  fips_enabled: false
  jolokia_enabled: true
  jmxexporter_enabled: true
  ssl_self_signed_ca_cert_filename: name-ca-1.crt
  ssl_self_signed_ca_key_filename: name-ca-1.key
   regenerate_ca: true
   ssl_self_signed_ca_password: somePassword
    kafka_broker_custom_listeners:
      internal:
        name: INTERNAL
        port: 9091
        ssl_enabled: false
        ssl_mutual_auth_enabled: false
        sasl_protocol: none
      external:
        name: EXTERNAL
        port: 9092
        ssl_enabled: true
        ssl_mutual_auth_enabled: false
      client_listener:
        name: CLIENT
        port: 9093
        ssl_enabled: true
        ssl_mutual_auth_enabled: true
        sasl_protocol: scram
```

**Comment by JumaX** [comment]
@DefunctExodus Looks like this has been discussed with @domenicbove and just resolved with the merger of https://github.com/confluentinc/cp-ansible/pull/185.

**Comment by DefunctExodus** [comment]
@JumaX  I saw the pull request and subscribed to it, just saw it get merged thanks
