### ISSUE TITLE
Enable TLS on running cluster with zero downtime is borked

### ISSUE THREAD

**Issue by erikgb** [confluentinc/cp-ansible#948]
**Describe the issue**
We are trying to enable TLS in a cluster with zero downtime, using the [documented approach](https://docs.confluent.io/ansible/current/ansible-zookeeper-tls.html#enable-zk-client-to-server-tls-encryption-and-authentication) for this, and are facing some issues:

When attempting to perform step 1, zookeeper provisioning goes well, and we can verify that after provisioning the zookeepers are listening on both plaintext and TLS ports. But in the initial stages of the broker provisioning, it fails when trying to determine the state of the running cluster (`dynamic_groups.yml`; serial provisioning enabled):
````log
TASK [confluent.kafka_broker : Get Controller Broker ID] ***********************
fatal: [REDACTED]: FAILED! => changed=false 
  cmd: |-
    set -o pipefail &&
      /usr/bin/zookeeper-shell REDACTED:2182        -zk-tls-config-file /etc/kafka/zookeeper-tls-client.properties      get /controller | grep brokerid
  delta: '0:00:01.143464'
  end: '2022-03-03 09:40:10.690963'
  msg: non-zero return code
  rc: 1
  start: '2022-03-03 09:40:09.547499'
  stderr: |-
    [2022-03-03 09:40:10,348] WARN Failed to initialize a channel. Closing: [id: 0xf52c10f5] (io.netty.channel.ChannelInitializer)
    org.apache.zookeeper.common.X509Exception$SSLContextException: Failed to create KeyManager
            at org.apache.zookeeper.common.X509Util.createSSLContextAndOptions(X509Util.java:336)
            at org.apache.zookeeper.common.X509Util.createSSLContext(X509Util.java:268)
            at org.apache.zookeeper.ClientCnxnSocketNetty$ZKClientPipelineFactory.initSSL(ClientCnxnSocketNetty.java:454)
            at org.apache.zookeeper.ClientCnxnSocketNetty$ZKClientPipelineFactory.initChannel(ClientCnxnSocketNetty.java:444)
            at org.apache.zookeeper.ClientCnxnSocketNetty$ZKClientPipelineFactory.initChannel(ClientCnxnSocketNetty.java:429)
            at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129)
            at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112)
            at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:938)
            at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609)
            at io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46)
            at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1463)
            at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1115)
            at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:650)
            at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:514)
            at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
            at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
            at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
            at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
            at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
            at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
            at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
            at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
            at java.base/java.lang.Thread.run(Thread.java:829)
    Caused by: org.apache.zookeeper.common.X509Exception$KeyManagerException: java.io.FileNotFoundException: /var/ssl/private/kafka_broker.keystore.jks (No such file or directory)
            at org.apache.zookeeper.common.X509Util.createKeyManager(X509Util.java:417)
            at org.apache.zookeeper.common.X509Util.createSSLContextAndOptions(X509Util.java:334)
            ... 22 more
    Caused by: java.io.FileNotFoundException: /var/ssl/private/kafka_broker.keystore.jks (No such file or directory)
            at java.base/java.io.FileInputStream.open0(Native Method)
            at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
            at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
            at org.apache.zookeeper.common.StandardTypeFileKeyStoreLoader.loadKeyStore(StandardTypeFileKeyStoreLoader.java:46)
            at org.apache.zookeeper.common.X509Util.createKeyManager(X509Util.java:406)
            ... 23 more
    [2022-03-03 09:40:10,364] WARN Session 0x0 for server REDACTED/REDACTED:2182, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
    java.lang.NullPointerException
            at org.apache.zookeeper.ClientCnxnSocketNetty.sendPkt(ClientCnxnSocketNetty.java:342)
            at org.apache.zookeeper.ClientCnxnSocketNetty.sendPktOnly(ClientCnxnSocketNetty.java:324)
            at org.apache.zookeeper.ClientCnxnSocketNetty.doWrite(ClientCnxnSocketNetty.java:368)
            at org.apache.zookeeper.ClientCnxnSocketNetty.doTransport(ClientCnxnSocketNetty.java:294)
            at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1223)
    org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /controller
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>
````

This seems to happen because the broker keystores/truststores are prepared later in the pipeline - triggered by the `zookeeper_ssl_enabled: true` property. So a classical chicken-egg problem. 😉

**To Reproduce**

1. Create a cluster without TLS enabled and `deployment_strategy` set to `serial`/`rolling`.
2. Attempt to enable the TLS port on zookeepers (in addition to the plaintext port) as described in [step 1 of the relevant docs](https://docs.confluent.io/ansible/current/ansible-zookeeper-tls.html#enable-zk-client-to-server-tls-encryption-and-authentication).

**Expected behaviour**

Zookeepers and brokers should be provisioned successfully with zero downtime. Brokers should be using TLS towards zookeepers.

**Inventory File**

Does not seem relevant. Please request details if needed.

**Logs**

Does not seem relevant. Please request details if needed.
**Environment (please complete the following information):**
 - OS: RHEL 8.5
 - CP-Ansible Branch: 6.2.2-post
 - Ansible Version: 2.11.9

**Additional context**

@nsharma-git made me aware of a potentially relevant PR: https://github.com/confluentinc/cp-ansible/pull/911. I think a viable solution to this issue, is to **use the zookeeper-client properties from server.properties as input to the `zookeeper-shell` command at this stage in the play** - at least when brokers are running and the deployment strategy is set to serial/rolling. The failing task is executed before any brokers in the cluster are provisioned......

**Comment by domenicbove** [comment]
@nsharma-git Looks like there is a docs bug, we need to mention that kafka must have ssl enabled in some fashion before performing those steps. A simple way workaround is to turn on ssl on a new listener. This will generate the keystores that @erikgb discovered are missing. Sorry I missed this case!

**Comment by erikgb** [comment]
I agree with @domenicbove that this is not strictly a bug. But it would be nice if cp-ansible failed more gracefully, so consider it an eventual improvement. 😄

In our case, we should have started with brokers; introducing at least one listener with TLS enabled. That should trigger the generation of keystores/truststores, and we would not have this trouble. But it would be nice if the docs mentioned this.

**Comment by nsharma-git** [comment]
Thanks @domenicbove . Does this mean that `kafka_broker_configure_multiple_listeners` has to be true.  And without this we wont be able to upgrade to TLS with zero down time.

@erikgb, suggestion noted. We will get the documents and failure message improved.

**Comment by nsharma-git** [comment]
@domenicbove Let me know your view
We need to get keystore and truststore generated on kafka broker before proceeding with TLS enablement. To get his done, we can either 
* enable ssl on one of the kafka listeners, if multiple listeners are configured.
* set the flag `kafka_broker_rest_ssl_enabled` to true 
With either the case, we want to run only ssl task and only on kafka. 
`ansible-playbook -i hosts.yml all.yml \
  --tags kafka_broker,ssl \
  --skip-tags package,zookeeper`

**Comment by domenicbove** [comment]
> @domenicbove Let me know your view We need to get keystore and truststore generated on kafka broker before proceeding with TLS enablement. To get his done, we can either
> 
> * enable ssl on one of the kafka listeners, if multiple listeners are configured.
> * set the flag `kafka_broker_rest_ssl_enabled` to true
>   With either the case, we want to run only ssl task and only on kafka.
> 
> ```
> ansible-playbook -i hosts.yml all.yml \
>   --tags kafka_broker,ssl \
>   --skip-tags package,zookeeper
> ```

yes that is correct. I dont think you need the skip-tags. I wonder if you run:
```
ansible-playbook -i hosts.yml all.yml \
  -e zookeeper_ssl_enabled=true \
   --tags kafka_broker,ssl
```

If that would generate the keystores and skip everything else (like the reconfiguration tasks). Really we are looking for anyway to get the keystores generated

**Comment by nsharma-git** [comment]
The document has been updated. Closing this as fixed.
